<?php

namespace ContainerXpJHRUh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\GalleryController' shared autowired service.
     *
     * @return \App\Controller\GalleryController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\GalleryController'] = $instance = new \App\Controller\GalleryController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\GalleryController', $container));

        return $instance;
    }
}
