<?php

namespace ContainerAnQgXQD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jpxqoq8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Jpxqoq8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jpxqoq8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'media' => ['privates', '.errored..service_locator.Jpxqoq8.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator.Jpxqoq8": it references class "App\\Entity\\Media" but no such service exists.'],
        ], [
            'media' => 'App\\Entity\\Media',
        ]);
    }
}
