<?php

namespace ContainerAnQgXQD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AACJXinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aACJXin' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aACJXin'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\APIController::saveArticle' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\APIController::saveMail' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\APIController::storeArticle' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController::delete' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController::edit' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController::index' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\CarouselLikeController::carouselDelete' => ['privates', '.service_locator.puq85cF', 'get_ServiceLocator_Puq85cFService', true],
            'App\\Controller\\DashboardController::login' => ['privates', '.service_locator._RztPCG', 'get_ServiceLocator_RztPCGService', true],
            'App\\Controller\\IndexController::login' => ['privates', '.service_locator.nyfkghW', 'get_ServiceLocator_NyfkghWService', true],
            'App\\Controller\\LogController::index' => ['privates', '.service_locator.XDBtZsA', 'get_ServiceLocator_XDBtZsAService', true],
            'App\\Controller\\MediaController::addMediaPage' => ['privates', '.service_locator.HI4VmaO', 'get_ServiceLocator_HI4VmaOService', true],
            'App\\Controller\\MediaController::deleteMediaFromGallery' => ['privates', '.service_locator.Jpxqoq8', 'get_ServiceLocator_Jpxqoq8Service', true],
            'App\\Controller\\MediaController::deleteMediaPage' => ['privates', '.service_locator.Jpxqoq8', 'get_ServiceLocator_Jpxqoq8Service', true],
            'App\\Controller\\UserController::changeProfilePicture' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\APIController:saveArticle' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\APIController:saveMail' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\APIController:storeArticle' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController:delete' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController:edit' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\ArticlesController:index' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'App\\Controller\\CarouselLikeController:carouselDelete' => ['privates', '.service_locator.puq85cF', 'get_ServiceLocator_Puq85cFService', true],
            'App\\Controller\\DashboardController:login' => ['privates', '.service_locator._RztPCG', 'get_ServiceLocator_RztPCGService', true],
            'App\\Controller\\IndexController:login' => ['privates', '.service_locator.nyfkghW', 'get_ServiceLocator_NyfkghWService', true],
            'App\\Controller\\LogController:index' => ['privates', '.service_locator.XDBtZsA', 'get_ServiceLocator_XDBtZsAService', true],
            'App\\Controller\\MediaController:addMediaPage' => ['privates', '.service_locator.HI4VmaO', 'get_ServiceLocator_HI4VmaOService', true],
            'App\\Controller\\MediaController:deleteMediaFromGallery' => ['privates', '.service_locator.Jpxqoq8', 'get_ServiceLocator_Jpxqoq8Service', true],
            'App\\Controller\\MediaController:deleteMediaPage' => ['privates', '.service_locator.Jpxqoq8', 'get_ServiceLocator_Jpxqoq8Service', true],
            'App\\Controller\\UserController:changeProfilePicture' => ['privates', '.service_locator.Ek1Bs8S', 'get_ServiceLocator_Ek1Bs8SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\APIController::saveArticle' => '?',
            'App\\Controller\\APIController::saveMail' => '?',
            'App\\Controller\\APIController::storeArticle' => '?',
            'App\\Controller\\ArticlesController::delete' => '?',
            'App\\Controller\\ArticlesController::edit' => '?',
            'App\\Controller\\ArticlesController::index' => '?',
            'App\\Controller\\CarouselLikeController::carouselDelete' => '?',
            'App\\Controller\\DashboardController::login' => '?',
            'App\\Controller\\IndexController::login' => '?',
            'App\\Controller\\LogController::index' => '?',
            'App\\Controller\\MediaController::addMediaPage' => '?',
            'App\\Controller\\MediaController::deleteMediaFromGallery' => '?',
            'App\\Controller\\MediaController::deleteMediaPage' => '?',
            'App\\Controller\\UserController::changeProfilePicture' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\APIController:saveArticle' => '?',
            'App\\Controller\\APIController:saveMail' => '?',
            'App\\Controller\\APIController:storeArticle' => '?',
            'App\\Controller\\ArticlesController:delete' => '?',
            'App\\Controller\\ArticlesController:edit' => '?',
            'App\\Controller\\ArticlesController:index' => '?',
            'App\\Controller\\CarouselLikeController:carouselDelete' => '?',
            'App\\Controller\\DashboardController:login' => '?',
            'App\\Controller\\IndexController:login' => '?',
            'App\\Controller\\LogController:index' => '?',
            'App\\Controller\\MediaController:addMediaPage' => '?',
            'App\\Controller\\MediaController:deleteMediaFromGallery' => '?',
            'App\\Controller\\MediaController:deleteMediaPage' => '?',
            'App\\Controller\\UserController:changeProfilePicture' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
