<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpJHRUh\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpJHRUh/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXpJHRUh.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXpJHRUh\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXpJHRUh\App_KernelProdContainer([
    'container.build_hash' => 'XpJHRUh',
    'container.build_id' => '19d08b26',
    'container.build_time' => 1607504638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpJHRUh');
