<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTP0cSS\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTP0cSS/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXTP0cSS.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXTP0cSS\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXTP0cSS\App_KernelProdContainer([
    'container.build_hash' => 'XTP0cSS',
    'container.build_id' => '7a8cfb37',
    'container.build_time' => 1603883439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTP0cSS');
