<?php

namespace ContainerOO0pio7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_QeYtGrvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.QeYtGrv' shared service.
     *
     * @return \App\Controller\KernelInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::changeProfilePicture()": the $kernel argument is type-hinted with the non-existent class or interface: "App\\Controller\\KernelInterface". Did you forget to add a use statement?');
    }
}
