<?php

namespace ContainerOO0pio7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselLikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HI4VmaO.App\Entity\CarouselLike' shared service.
     *
     * @return \App\Entity\CarouselLike
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HI4VmaO": it references class "App\\Entity\\CarouselLike" but no such service exists.');
    }
}
