<?php

namespace ContainerOO0pio7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MediaFormType' shared autowired service.
     *
     * @return \App\Form\MediaFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MediaFormType.php';

        return $container->privates['App\\Form\\MediaFormType'] = new \App\Form\MediaFormType();
    }
}
