<?php

namespace Container7Pams19;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HI4VmaOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HI4VmaO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HI4VmaO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carouselLike' => ['privates', '.errored..service_locator.HI4VmaO.App\\Entity\\CarouselLike', NULL, 'Cannot autowire service ".service_locator.HI4VmaO": it references class "App\\Entity\\CarouselLike" but no such service exists.'],
        ], [
            'carouselLike' => 'App\\Entity\\CarouselLike',
        ]);
    }
}
