<?php

namespace Container7Pams19;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDBtZsAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XDBtZsA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XDBtZsA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logRepository' => ['privates', 'App\\Repository\\LogRepository', 'getLogRepositoryService', true],
        ], [
            'logRepository' => 'App\\Repository\\LogRepository',
        ]);
    }
}
