<?php

namespace Container7Pams19;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ucPal8z.App\Entity\Link' shared service.
     *
     * @return \App\Entity\Link
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ucPal8z": it references class "App\\Entity\\Link" but no such service exists.');
    }
}
