<?php

namespace ContainerXTP0cSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SettingsRepository' shared autowired service.
     *
     * @return \App\Repository\SettingsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SettingsRepository'] = new \App\Repository\SettingsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
