<?php

namespace ContainerXTP0cSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SettingsController' shared autowired service.
     *
     * @return \App\Controller\SettingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SettingsController'] = $instance = new \App\Controller\SettingsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SettingsController', $container));

        return $instance;
    }
}
