<?php

namespace ContainerZ5SHqle;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailingListRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MailingListRepository' shared autowired service.
     *
     * @return \App\Repository\MailingListRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MailingListRepository'] = new \App\Repository\MailingListRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
