<?php

namespace ContainerZ5SHqle;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\NewsController' shared autowired service.
     *
     * @return \App\Controller\NewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\NewsController'] = $instance = new \App\Controller\NewsController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\NewsController', $container));

        return $instance;
    }
}
