<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL0tG87h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL0tG87h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL0tG87h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL0tG87h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL0tG87h\App_KernelDevDebugContainer([
    'container.build_hash' => 'L0tG87h',
    'container.build_id' => '7bd5b919',
    'container.build_time' => 1603800422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL0tG87h');
