<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqW3kcq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqW3kcq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqW3kcq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqW3kcq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqW3kcq\App_KernelDevDebugContainer([
    'container.build_hash' => 'IqW3kcq',
    'container.build_id' => '68409661',
    'container.build_time' => 1612270055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqW3kcq');
