<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxifLdR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxifLdR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxifLdR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxifLdR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxifLdR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxifLdR',
    'container.build_id' => 'e3e5ff37',
    'container.build_time' => 1610014926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxifLdR');
