<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFiQyYp4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFiQyYp4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFiQyYp4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFiQyYp4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFiQyYp4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FiQyYp4',
    'container.build_id' => '5810ca65',
    'container.build_time' => 1612302622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFiQyYp4');
