<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'check_oldpassword' => [[], ['_controller' => 'App\\Controller\\APIController::checkOldPassword'], [], [['text', '/api/checkoldpassword']], [], []],
    'updatepassword' => [[], ['_controller' => 'App\\Controller\\APIController::updatePassword'], [], [['text', '/api/updatepassword']], [], []],
    'check_username' => [[], ['_controller' => 'App\\Controller\\APIController::checkUsername'], [], [['text', '/api/checkusername']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], []],
    'login_if_not_connected' => [[], ['_controller' => 'App\\Controller\\DashboardController::login'], [], [['text', '/login']], [], []],
    'ERROR_401' => [[], ['_controller' => 'App\\Controller\\ErrorController::ERROR401'], [], [['text', '/401']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\IndexController::login'], [], [['text', '/fastlogin']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\IndexController::logout'], [], [['text', '/logout']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\IndexController::register'], [], [['text', '/register']], [], []],
    'settings' => [[], ['_controller' => 'App\\Controller\\SettingsController::index'], [], [['text', '/dashboard/settings']], [], []],
    'settings_save' => [['id'], ['_controller' => 'App\\Controller\\SettingsController::saveSettings'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/export/settings/save']], [], []],
    'account' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/dashboard/account']], [], []],
    'users' => [[], ['_controller' => 'App\\Controller\\UserController::users'], [], [['text', '/dashboard/users']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/control/admin/users/delete']], [], []],
    'user_executeAction' => [[], ['_controller' => 'App\\Controller\\UserController::executeAction'], [], [['text', '/control/admin/users/executeAction']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], []],
];
