name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PTUTS3S4 on SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            symfony server:stop
            killall -9 symfony
            cd /home/ptuts3s4
            git reset --hard
            git clean -fd
            git pull
            composer install
            symfony server:start --port=5555 --daemon
            php bin/console doctrine:database:drop --force
            php bin/console doctrine:database:create
            php bin/console doctrine:migrations:migrate --no-interaction
            php bin/console doctrine:fixtures:load --no-interaction