name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PTUTS3S4 on SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            symfony server:stop
            pm2 delete 0
            cd /home/ptuts3s4
            git reset --hard
            git clean -fd
            git pull
            pm2 start --name="PTUT S3S4" "symfony server:start --port=5555 --daemon"